msg = input("Digite algo: ")
print(msg)
print(type(msg))
print('É alfabético? ', msg.isalpha())
print('É alfanumérico? ', msg.isalnum())
print('Só tem espaços? ', msg.isspace())
print('Está em maiúsculas?', msg.isupper())
print('Está em minúsculas?', msg.islower())
print('Está capitalizada?', msg.istitle())
print('É um número?', msg.isnumeric())
